# Generated by Django 5.2.8 on 2025-11-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='app_name',
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('category', 'Category'), ('content', 'Content')], default='category', verbose_name='Category type'),
        ),
    ]
