# Generated by Django 5.2.8 on 2025-11-08 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_category_app_name_category_category_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='content',
            unique_together={('category', 'slug')},
        ),
    ]
