# Generated by Django 5.2.8 on 2025-11-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('category', 'Category'), ('content', 'Content'), ('link', 'Link')], default='category', verbose_name='Category type'),
        ),
    ]
