# Generated by Django 5.2.8 on 2025-11-08 18:24

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_category_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headliner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('title_kk', models.CharField(max_length=64, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=64, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=64, null=True, verbose_name='Title')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='register/public/headliners/', validators=[core.validators.validate_poster], verbose_name='Poster')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('about_kk', models.TextField(blank=True, null=True, verbose_name='About')),
                ('about_ru', models.TextField(blank=True, null=True, verbose_name='About')),
                ('about_en', models.TextField(blank=True, null=True, verbose_name='About')),
                ('src', models.CharField(default='/', max_length=128, verbose_name='Source URL')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('is_archive', models.BooleanField(default=False, verbose_name='Is archive')),
            ],
            options={
                'verbose_name': 'Headliner',
                'verbose_name_plural': 'Headliners',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='Label')),
                ('label_kk', models.CharField(max_length=128, null=True, verbose_name='Label')),
                ('label_ru', models.CharField(max_length=128, null=True, verbose_name='Label')),
                ('label_en', models.CharField(max_length=128, null=True, verbose_name='Label')),
                ('url', models.URLField(verbose_name='URL')),
                ('target', models.BooleanField(default=False, verbose_name='Target')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
            },
        ),
    ]
