# Generated by Django 5.2.8 on 2025-11-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_headliner_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Order'),
        ),
    ]
