# Generated by Django 5.2.8 on 2025-11-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_resource_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ('order',), 'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
        migrations.RemoveField(
            model_name='headliner',
            name='src',
        ),
        migrations.AddField(
            model_name='headliner',
            name='url',
            field=models.CharField(default='/', max_length=128, verbose_name='URL'),
        ),
    ]
