# Generated by Django 5.2.8 on 2025-11-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_resource_options_remove_headliner_src_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecontent',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='core/content/category/files/', verbose_name='Source file'),
        ),
        migrations.AlterField(
            model_name='filecontent',
            name='source_file_en',
            field=models.FileField(blank=True, null=True, upload_to='core/content/category/files/', verbose_name='Source file'),
        ),
        migrations.AlterField(
            model_name='filecontent',
            name='source_file_kk',
            field=models.FileField(blank=True, null=True, upload_to='core/content/category/files/', verbose_name='Source file'),
        ),
        migrations.AlterField(
            model_name='filecontent',
            name='source_file_ru',
            field=models.FileField(blank=True, null=True, upload_to='core/content/category/files/', verbose_name='Source file'),
        ),
    ]
