# Generated by Django 5.2.8 on 2025-11-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_filecontent_source_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='target',
            field=models.BooleanField(default=False, verbose_name='New tab'),
        ),
    ]
