# Generated by Django 5.2.8 on 2025-11-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_textcontent_text_alter_textcontent_text_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcontent',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='text_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
    ]
