# Generated by Django 5.2.8 on 2025-11-09 15:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_textcontent_text_alter_textcontent_text_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcontent',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='text_kk',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
    ]
